set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports CLK];    #IO_L12P_T1_MRCC_35 Sch=clk100mhz
create_clock -period 10.00 -name sys_clk_pin -waveform {0 5} -add [get_ports CLK]

set_property -dict { PACKAGE_PIN C12   IOSTANDARD LVCMOS33 } [get_ports RESET];  #IO_L3P_T0_DQS_AD1P_15 Sch=cpu_resetn

set_property PACKAGE_PIN C6 [get_ports {PORTOUT[0]}]
set_property PACKAGE_PIN V17 [get_ports uart0_rxd]
set_property PACKAGE_PIN V16 [get_ports uart0_txd]
set_property PACKAGE_PIN A3 [get_ports {PORTIN[15]}]
set_property PACKAGE_PIN A4 [get_ports {PORTIN[14]}]
set_property PACKAGE_PIN A5 [get_ports {PORTIN[13]}]
set_property PACKAGE_PIN A6 [get_ports {PORTIN[12]}]
set_property PACKAGE_PIN A8 [get_ports {PORTIN[11]}]
set_property PACKAGE_PIN A9 [get_ports {PORTIN[10]}]
set_property PACKAGE_PIN A10 [get_ports {PORTIN[9]}]
set_property PACKAGE_PIN A13 [get_ports {PORTIN[8]}]
set_property PACKAGE_PIN A14 [get_ports {PORTIN[7]}]
set_property PACKAGE_PIN A15 [get_ports {PORTIN[6]}]
set_property PACKAGE_PIN A16 [get_ports {PORTIN[5]}]
set_property PACKAGE_PIN A18 [get_ports {PORTIN[4]}]
set_property PACKAGE_PIN B1 [get_ports {PORTIN[3]}]
set_property PACKAGE_PIN B3 [get_ports {PORTIN[2]}]
set_property PACKAGE_PIN B2 [get_ports {PORTIN[1]}]
set_property PACKAGE_PIN A1 [get_ports {PORTIN[0]}]
set_property PACKAGE_PIN B4 [get_ports {PORTOUT[15]}]
set_property PACKAGE_PIN B6 [get_ports {PORTOUT[14]}]
set_property PACKAGE_PIN B7 [get_ports {PORTOUT[13]}]
set_property PACKAGE_PIN B8 [get_ports {PORTOUT[12]}]
set_property PACKAGE_PIN B9 [get_ports {PORTOUT[11]}]
set_property PACKAGE_PIN B11 [get_ports {PORTOUT[10]}]
set_property PACKAGE_PIN B12 [get_ports {PORTOUT[9]}]
set_property PACKAGE_PIN B13 [get_ports {PORTOUT[8]}]
set_property PACKAGE_PIN B14 [get_ports {PORTOUT[7]}]
set_property PACKAGE_PIN B16 [get_ports {PORTOUT[6]}]
set_property PACKAGE_PIN B17 [get_ports {PORTOUT[5]}]
set_property PACKAGE_PIN B18 [get_ports {PORTOUT[4]}]
set_property PACKAGE_PIN C1 [get_ports {PORTOUT[3]}]
set_property PACKAGE_PIN C2 [get_ports {PORTOUT[2]}]
set_property PACKAGE_PIN C4 [get_ports {PORTOUT[1]}]

set_property DIRECTION IN [get_ports {PORTIN[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[15]}]
set_property DIRECTION IN [get_ports {PORTIN[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[14]}]
set_property DIRECTION IN [get_ports {PORTIN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[13]}]
set_property DIRECTION IN [get_ports {PORTIN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[12]}]
set_property DIRECTION IN [get_ports {PORTIN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[11]}]
set_property DIRECTION IN [get_ports {PORTIN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[10]}]
set_property DIRECTION IN [get_ports {PORTIN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[9]}]
set_property DIRECTION IN [get_ports {PORTIN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[8]}]
set_property DIRECTION IN [get_ports {PORTIN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[7]}]
set_property DIRECTION IN [get_ports {PORTIN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[6]}]
set_property DIRECTION IN [get_ports {PORTIN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[5]}]
set_property DIRECTION IN [get_ports {PORTIN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[4]}]
set_property DIRECTION IN [get_ports {PORTIN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[3]}]
set_property DIRECTION IN [get_ports {PORTIN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[2]}]
set_property DIRECTION IN [get_ports {PORTIN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[1]}]
set_property DIRECTION IN [get_ports {PORTIN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTIN[0]}]
set_property DIRECTION OUT [get_ports {PORTOUT[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[15]}]
set_property DRIVE 12 [get_ports {PORTOUT[15]}]
set_property SLEW SLOW [get_ports {PORTOUT[15]}]
set_property DIRECTION OUT [get_ports {PORTOUT[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[14]}]
set_property DRIVE 12 [get_ports {PORTOUT[14]}]
set_property SLEW SLOW [get_ports {PORTOUT[14]}]
set_property DIRECTION OUT [get_ports {PORTOUT[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[13]}]
set_property DRIVE 12 [get_ports {PORTOUT[13]}]
set_property SLEW SLOW [get_ports {PORTOUT[13]}]
set_property DIRECTION OUT [get_ports {PORTOUT[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[12]}]
set_property DRIVE 12 [get_ports {PORTOUT[12]}]
set_property SLEW SLOW [get_ports {PORTOUT[12]}]
set_property DIRECTION OUT [get_ports {PORTOUT[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[11]}]
set_property DRIVE 12 [get_ports {PORTOUT[11]}]
set_property SLEW SLOW [get_ports {PORTOUT[11]}]
set_property DIRECTION OUT [get_ports {PORTOUT[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[10]}]
set_property DRIVE 12 [get_ports {PORTOUT[10]}]
set_property SLEW SLOW [get_ports {PORTOUT[10]}]
set_property DIRECTION OUT [get_ports {PORTOUT[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[9]}]
set_property DRIVE 12 [get_ports {PORTOUT[9]}]
set_property SLEW SLOW [get_ports {PORTOUT[9]}]
set_property DIRECTION OUT [get_ports {PORTOUT[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[8]}]
set_property DRIVE 12 [get_ports {PORTOUT[8]}]
set_property SLEW SLOW [get_ports {PORTOUT[8]}]
set_property DIRECTION OUT [get_ports {PORTOUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[7]}]
set_property DRIVE 12 [get_ports {PORTOUT[7]}]
set_property SLEW SLOW [get_ports {PORTOUT[7]}]
set_property DIRECTION OUT [get_ports {PORTOUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[6]}]
set_property DRIVE 12 [get_ports {PORTOUT[6]}]
set_property SLEW SLOW [get_ports {PORTOUT[6]}]
set_property DIRECTION OUT [get_ports {PORTOUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[5]}]
set_property DRIVE 12 [get_ports {PORTOUT[5]}]
set_property SLEW SLOW [get_ports {PORTOUT[5]}]
set_property DIRECTION OUT [get_ports {PORTOUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[4]}]
set_property DRIVE 12 [get_ports {PORTOUT[4]}]
set_property SLEW SLOW [get_ports {PORTOUT[4]}]
set_property DIRECTION OUT [get_ports {PORTOUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[3]}]
set_property DRIVE 12 [get_ports {PORTOUT[3]}]
set_property SLEW SLOW [get_ports {PORTOUT[3]}]
set_property DIRECTION OUT [get_ports {PORTOUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[2]}]
set_property DRIVE 12 [get_ports {PORTOUT[2]}]
set_property SLEW SLOW [get_ports {PORTOUT[2]}]
set_property DIRECTION OUT [get_ports {PORTOUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[1]}]
set_property DRIVE 12 [get_ports {PORTOUT[1]}]
set_property SLEW SLOW [get_ports {PORTOUT[1]}]
set_property DIRECTION OUT [get_ports {PORTOUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PORTOUT[0]}]
set_property DRIVE 12 [get_ports {PORTOUT[0]}]
set_property SLEW SLOW [get_ports {PORTOUT[0]}]

set_property DIRECTION IN [get_ports uart0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_rxd]
set_property DIRECTION OUT [get_ports uart0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_txd]
set_property DRIVE 12 [get_ports uart0_txd]
set_property SLEW SLOW [get_ports uart0_txd]

set_property -dict { PACKAGE_PIN H4    IOSTANDARD LVCMOS33 } [get_ports TMS];    #IO_L21N_T3_DQS_35 Sch=jd[1]
set_property -dict { PACKAGE_PIN H1    IOSTANDARD LVCMOS33 } [get_ports TDI];    #IO_L17P_T2_35 Sch=jd[2]
set_property -dict { PACKAGE_PIN G1    IOSTANDARD LVCMOS33 } [get_ports TDO];    #IO_L17N_T2_35 Sch=jd[3]
set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports TCK];    #IO_L20N_T3_35 Sch=jd[4]
set_property -dict { PACKAGE_PIN A1    IOSTANDARD LVCMOS33 } [get_ports PORTOUT[0]];
create_clock -period 20.00 -name dbg_tck_pin -waveform {0 10} -add [get_ports TCK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets TCK]

